import type { Metadata } from "next";
import "@/styles/reset.css";
import "@/styles/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="bg-gray-50">
        <Header />
        <div className="my-6 md:w-full lg:w-[1200px] lg:mx-auto">
          {children}
        </div>
      </body>
    </html>
  );
}
