import localFont from "next/font/local";

import type { Metadata } from "next";

import "./globals.css";
import Header from "@/components/Header";
import QueryProvider from "@/app/_components/QueryProvider";
import ToastContainer from "@/components/Toast/ToastContainer";

const nanumsquare = localFont({
  src: [
    {
      path: "../../public/fonts/NanumSquareR.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/NanumSquareB.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/fonts/NanumSquareEB.woff",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-nanumsquare",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${nanumsquare.className} bg-gray-50`}>
        <QueryProvider>
          <Header />
          <div className="max-w-[1200px] mx-auto">{children}</div>
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
